services:
  ollama-setup:
    image: ollama/ollama:latest
    volumes:
      - ollama-models:/root/.ollama
    environment:
      - OLLAMA_NUM_THREADS=9
    entrypoint: >-
      sh -c "
      ollama serve &
      sleep 10 &&
      ollama pull deepseek-r1:1.5b &&
      pkill ollama
      "
    healthcheck:
      test: ["CMD", "test", "-f", "/root/.ollama/models/manifests/registry.ollama.ai/library/deepseek-r1/1.5b"]
      interval: 10s
      timeout: 5s
      retries: 10



  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_NUM_THREADS=9
    volumes:
      - ollama-models:/root/.ollama
    command: >-
      serve
    depends_on:
      ollama-setup:
        condition: service_healthy

  postgres:
    build: 
      context: .
      dockerfile: dockerfile.database
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=admin
      - POSTGRES_DB=vectordbtest
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/data
      - ./postgres:/backups
  pgAdmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@test.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    volumes:
      - ./pgAdmin:/pgAdmin
      - ./pgAdmin:/backups
volumes:
  ollama-models:
  postgres:
  pgAdmin:
